---
extends: default

ignore: |
  build/
  .github/

rules:
  line-length: disable
  trailing-spaces:
    level: warning
  new-line-at-end-of-file:
    level: warning
  empty-lines:
    level: warning
